-- ksql query to create a stream for telegram bot outbox
CREATE STREAM telegram_outbox (
`chat_id` VARCHAR,
`text` VARCHAR
) WITH (
  KAFKA_TOPIC = 'telegram_outbox',
  PARTITIONS = 1,
  VALUE_FORMAT = 'avro'
 );

INSERT INTO telegram_outbox
SELECT
'6859366896' as `chat_id`,
CONCAT
(
  'Likes changed: ',
  CAST(likes_previous AS STRING),
  ' => ',
  CAST(likes_current AS STRING),
  '. ',
  title
) AS `text`
FROM  YOUTUBE_CHANGES_STREAM
WHERE likes_current <> likes_previous;

CREATE TABLE YOUTUBE_CHANGES WITH (CLEANUP_POLICY='compact', KAFKA_TOPIC='youtube_changes', PARTITIONS=1, REPLICAS=3, RETENTION_MS=604800000) AS SELECT
  YOUTUBE_VIDEOS.VIDEO_ID VIDEO_ID,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.TITLE) TITLE,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[1] COMMENTS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.COMMENTS, 2)[2] COMMENTS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[1] VIEWS_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.VIEWS, 2)[2] VIEWS_CURRENT,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[1] LIKES_PREVIOUS,
  LATEST_BY_OFFSET(YOUTUBE_VIDEOS.LIKES, 2)[2] LIKES_CURRENT
FROM YOUTUBE_VIDEOS YOUTUBE_VIDEOS
GROUP BY YOUTUBE_VIDEOS.VIDEO_ID
EMIT CHANGES;